<?php
/**
 * Implements hook_menu
 */
function autoredirect_menu() {
  $items = array();
  $items['autoredirect/403'] = array(
    'title' => t('Access Denied'),
    'page callback' => 'autoredirect_403',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function autoredirect_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $site_403 = variable_get('site_403', '');
  //Instructions element
  $form['error_page']['autoredirect_instructions'] = array(
    '#type' => 'markup',
    '#prefix' => '<h5>Autoredirect Module has been installed!</h5>',
    '#markup' => 'This module provides a mechanism for redirecting 403 pages',
  );
  $form['error_page']['autoredirect_instructions']['#markup'] .= ' which normally would not feature content.';
  $form['error_page']['autoredirect_instructions']['#markup'] .= ' You can enable this feature by entering the path';
  $form['error_page']['autoredirect_instructions']['#markup'] .= ' "autoredirect/403" for the 403 page.' ;
  // 403 form processing
  $form['error_page']['site_403']['#weight'] = 10;
  //404 form processing
  $form['error_page']['site_404']['#weight'] = 20;
  // 403 redirects by content type
  if($site_403 == 'autoredirect/403') {
    $types = node_type_get_types();
    $form['error_page']['autoredirect_403'] = array(
      '#type' => 'fieldset',
      '#collapsed' => TRUE,
      '#collapsible' => TRUE,
      '#title' => 'Autoredirect 403 Errors',
      '#weight' => 15,
    );
    foreach($types as $type => $obj) {
      $form['error_page']['autoredirect_403']['autoredirect_403_'.$type] = array(
        '#type' => 'textfield',
        '#title' => $obj->name,
        '#description' => t('Redirect 403 pages to the following path.'),
        '#default_value' => variable_get('autoredirect_403_'.$type, ''),
      );
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function autoredirect_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'autoredirect_404_variable_set';
  $form['autoredirect'] = array(
    '#type' => 'fieldset',
    '#title' => t('Autoredirect Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
  );
  if(!empty($form['#node_type']) && module_exists('redirect')) {
    $form['autoredirect']['autoredirect_404_'.$form['#node_type']->type] = array(
      '#type' => 'textfield',
      '#title' => t('404 Redirect Path'),
      '#description' => t('When nodes of this type are deleted, a redirect to this path will be created'),
      '#default_value' => variable_get('autoredirect_404_'.$form['#node_type']->type, ''),
    );
  } else {
    $form['autoredirect']['autoredirect_config_needed'] = array(
      '#type' => 'markup',
      '#markup' => t('Please save this content type and enable the redirect module to configure 404 handling.'),
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function autoredirect_form_node_delete_confirm_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'autoredirect_404_generate';
}

/**
 * 403 Callback
 */
function autoredirect_403() {
  if($obj = autoredirect_is_node()) {
    $redirect_path = variable_get('autoredirect_403_'.$obj->type, '');
    if(!empty($redirect_path)) {
      unset($_GET['destination']);
      $status_code = 302;
      drupal_alter('autoredirect_403_status', $status_code, $obj, $redirect_path);
      drupal_goto($redirect_path, array(), $status_code);
    }
  }
  drupal_access_denied();
}

/**
 * Set variables for 404
 */
function autoredirect_404_variable_set(&$form, &$form_state) {
  $type = 'autoredirect_404_'.$form['#node_type']->type;
  if(!empty($form_state['values'][$type])) {
    variable_set($type, $form_state['values'][$type]);
  }
}

/**
 * Helper for picking out node menu items
 */
function autoredirect_is_node() {
  $prev = drupal_get_destination();
  $item = menu_get_item($prev['destination']);
  if($item['path'] === 'node/%') {
    $node = node_load($item['original_map'][1]);
    return $node;
  } else {
    return FALSE;
  }
}

/**
 * Implements hook_node_delete
 */
function autoredirect_404_generate(&$form, &$form_state) {
  $node = $form['#node'];
  $opt = variable_get('autoredirect_404_'.$node->type, '');
  if(!empty($opt) && module_exists('redirect')) {
    $redirect = new stdClass();
    $source = redirect_parse_url('node/'.$node->nid);
    $destination = redirect_parse_url($opt);
    redirect_object_prepare($redirect);
    $redirect->source = $source['url'];
    $redirect->redirect = $destination['url'];
    redirect_save($redirect);
    drupal_set_message('Redirect created for: '.$node->title, 'status');
  }
}